feat: add Rocket.chat support
containrrr/shoutrrr pull request #64
Opened 2020-09-28 14:18 UTC by dmitry-kovalev

2020-10-03 17:18 UTC, piksel requested changes
Some copy/paste errors and needs some description. 

Adding docs on how to set it up would be nice too, but is not a requirement. Linking to the official documentation and/or describing the service would suffice as a description.

2020-10-03 17:18 UTC, piksel commented on pkg/services/rocketchat/rocketchat.go
> +// Send a notification message to Slack
```suggestion
// Send a notification message to Rocket Chat
```

2020-10-03 17:18 UTC, piksel commented on pkg/services/rocketchat/rocketchat_config.go
> +// rocketchat://rocketchat.my-domain.com/tokenA/tokenB
These comments should probably not be here?

2020-10-03 17:18 UTC, piksel commented on pkg/services/rocketchat/rocketchat_test.go
> +		envRocketchatURL, _ = url.Parse(os.Getenv("SHOUTRRR_MATTERMOST_URL"))
```suggestion
		envRocketchatURL, _ = url.Parse(os.Getenv("SHOUTRRR_ROCKETCHAT_URL"))
```

2020-10-05 07:05 UTC, dmitry-kovalev commented
I've resolved all comments in one commit and added documentation on Rocket.chat integration.

2020-10-06 12:29 UTC, piksel commented on docs/services/overview.md
> +| [Rocketchat](./not-documented.md) | *rocketchat://[__`username`__@]__`rocketchat-host`__/__`token`__[/__`channel`&#124;`@recipient`__]*
```suggestion
| [Rocketchat](./rocketchat.md) | *rocketchat://[__`username`__@]__`rocketchat-host`__/__`token`__[/__`channel`&#124;`@recipient`__]*                                                               |
```

2020-10-06 12:31 UTC, piksel approved these changes
Looks good!

The documentation should probably be linked instead of `not-documented.md` though.

2020-10-08 17:08 UTC, merged